FROM gcc:latest

RUN apt-get update && apt-get install -y cmake

WORKDIR /usr/myapp

COPY /src ./src


#RUN cmake ./src/CMakeLists.cppclient.txt && make
RUN cmake ./src/CMakeLists.txt && make

ENTRYPOINT [ "./runProject" ]
